export default Object.freeze({
    HOME: "Home",
    LISTINGS: "Listings",
    LISTING_DETAIL: "ListingDetail",
    PROFILE: "Profile",
    FAVOURITES: "Favourites",
    CART: "Cart",
    CHECK_OUT_PAYMENT: "checkOutPayment",
    CHECK_OUT_ADDRESS: "checkOutAddress",
    CHECK_OUT_CONFIRM_ORDER: "checkOutConfirmOrder",
    LOGIN: "Login",
    CHECKOUT: "checkout",
    APPNAVIGATOR: "appNavigator",
    ADDRESSFORMSCREEN: "addressFormScreen",
    SELECTBILLINGADDRESS: "selectBillingAddress",
    FILTER: "filter",
    ORDERS: "orders",
    LOGIN_PHONE_NUMBER: "loginPhoneNumber",
    LOGIN_PASSWORD: "loginPassword"
})